### PR TITLE
Make `aw_get_segments` support named character vectors

### LINKED ISSUE #112: `aw_segment_table` fails with named vectors of segments
It's common for us at IXIS to organize our segments as named character vectors. This should be allowed, and should potentially override the automatic renaming that occurs in this function (with a consequent speed increase, I think?) 

```r
# Works
aw_segment_table(
  segmentIds = c("s1383_5a5f8f3601c1ebaa704c7818")
)

# Fails
aw_segment_table(
  segmentIds = c("_Inventory Results Page (Hit)" = "s1383_5a5f8f3601c1ebaa704c7818")
)
```

### PR DESCRIPTION
**Pull request by charlie-gallagher**
## Summary
- Resolves #112 and #113
- Adds `curl` to list of dependencies (not a stretch, since it's used a lot by `httr`)
- Adds parameter parsing function (that might be good to use in other functions)

### Still to-do
- Apply parameter parser function to other functions that build parameters

### Checks
- [x] Passed R CMD check with 0 errors, 0 warnings, and 0 notes
- [x] Tried a few queries for segments with different arrangements, but did not systematically test

### CODE REVIEW

**Review by benrwoodard — CHANGES_REQUESTED** [review]
There are a few arguments that need to be able to accept a character vector of values. For instance, the argument 'expansion' must be able to accept multiple values in a  character vector but it doesn't appear to be able to do that with these changes.

**Comment by charlie-gallagher** [comment]
Thanks for the quick response! Could you send me an example of a query that didn't work for you? I had a different result -- the following query worked for me. 

```r
segs <- aw_get_segments(
  rsids = "audiagaoa-t1-t2-t3-global-prod",
  segmentFilter = c("s1383_5a5f8f3601c1ebaa704c7818", "s1383_5a96d6ff55bf159e9f4bc707"),
  expansion = c("reportSuiteName", "ownerFullName", "definitionLastModified")
)

str(segs)

## 'data.frame':	2 obs. of  8 variables:
##  $ name                  : chr  "_Inventory Results Page (Hit)" "_Inventory - New (Hit)"
##  $ description           : chr  "Status: PROD | Instead Use:  | Scope: T1 | Logic: Tracks unique visitors to any inventory results page. Includi"| __truncated__ "New Inventory Hits"
##  $ id                    : chr  "s1383_5a5f8f3601c1ebaa704c7818" "s1383_5a96d6ff55bf159e9f4bc707"
##  $ definitionLastModified: chr  "2021-12-02T17:36:16Z" "2021-12-03T16:21:05Z"
##  $ reportSuiteName       : chr  "AoA Cross-Tier Prod" "AoA Cross-Tier Prod"
##  $ siteTitle             : chr  "AoA Cross-Tier Prod" "AoA Cross-Tier Prod"
##  $ rsid                  : chr  "audiagaoa-t1-t2-t3-global-prod" "audiagaoa-t1-t2-t3-global-prod"
##  $ owner                 :'data.frame':	2 obs. of  3 variables:
##   ..$ id   : int  000000 000000
##   ..$ name : chr  "anonymized" "anonymized"
##   ..$ login: chr  "anonymized" "anonymized"
```

There could be some other interaction that's causing problems.

**Review by benrwoodard — APPROVED** [review]

**Comment by benrwoodard** [comment]
You are correct, I was testing the new function that creates the query string and left out a key part of the process.  

In the previous process we were removing all parameters with NA on line 66
```
  #Turn the list into a string to create the query
  prequery <- list(vars %>% dplyr::select_if(~ !any(is.na(.))))
```

My query was this.  If I did not include a segmentFilter it did not return any segments.  The expected behavior is that if you do not add a value for rsids or segmentFilter, it will return all the segments up to the limit defined.
```
aw_get_segments(limit = 1000, rsid = 'ageo1xxpnwsdi2020prod')
```

**Comment by charlie-gallagher** [comment]
@benrwoodard Thanks for pointing that out, the most recent version should do this. One change is I made the default value for the arguments to `aw_get_segments` `NULL` instead of `NA`, so they're removed with `purrr::compact()`. Then I added an `assert_that` clause that fails when all values are `NA`. 

Maybe this is too big a change from existing behavior. We can make it work with `NA`s as the default, too, I just felt this gave us clearer conditions. 

In general, how would you prefer we handle these?

- NULL being passed as an argument
- One NA being passed as an argument
- A vector of NAs being passed as an argument

**Comment by charlie-gallagher** [comment]
@benrwoodard I extended the `format_URL_parameters` function so that it now collapses string vectors automatically into comma separated lists. This really simplifies functions like `aw_get_segments`, so I went ahead and updated all of the other "get" functions to match. 

**Typical old behavior:**

- Vectors containing NAs caused an API error
- NA was the default value for optional values
- Named vectors caused the query to fail

**New behavior:**

- A vector with all `NA`s is considered an error
- Otherwise, `NA`s are converted to the string "NA"
- `NULL` is the default value for optional values
- Named character vectors are handled as expected

### Checklist 

- [x] Updated documentation
- [x] R CMD check ran with 0 errors, 0 warnings, 0 notes

**Pull request merged**
